# Generated by Django 4.0 on 2021-12-08 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_library_delete_book_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='library',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
